#!/usr/bin/env bash
#
# ==================================================================
# go
# ==================================================================
# swarm-kit - Description
#
# File:         go
# Author:       Ragdata
# Date:         02/02/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren Poulton (Ragdata)
# ==================================================================

# ------------------------------------------------------------------
# FUNCTIONS
# ------------------------------------------------------------------
#
# INSTALL FUNCTION
#
go-install()
{
    echoLog "spacer"

    aptInstall golang-go

    echoLog "spacer"
}
#
# CONFIG FUNCTION
#
go-config()
{
    echoLog "spacer"

    echoLog "No Config Requirement"

    echoLog "spacer"
}
#
# REMOVE FUNCTION
#
go-remove()
{
    echoLog "spacer"

    aptRemove golang-go

    echoLog "spacer"
}
