#!/usr/bin/env bash
# shellcheck disable=SC2016
# ==================================================================
# go
# ==================================================================
# swarm-kit - Description
#
# File:         go
# Author:       Ragdata
# Date:         02/02/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren Poulton (Ragdata)
# ==================================================================

# ------------------------------------------------------------------
# FUNCTIONS
# ------------------------------------------------------------------
#
# INSTALL FUNCTION
#
go-install()
{
    echoLog "spacer"

    # create user downloads directory
    echoLog "Creating User Downloads Directory ..."
    mkdir -p ~/downloads
    # change to user downloads directory
    cd ~/downloads || return 1
    # download latest tarball
    echoLog "spacer"
    echoLog "Downloading Latest GO Tarball" --color=gold
    wget https://go.dev/dl/go1.19.5.linux-amd64.tar.gz
    echoLog "spacer"
    # untar to /usr/local
    echoLog "Inflating Tarball ..."
    sudo tar -C /usr/local -xvf go1.19.5.linux-amd64.tar.gz
    # return to working directory
    cd "$PWD" || return 1

    echoLog "spacer"
}
#
# CONFIG FUNCTION
#
go-config()
{
    echoLog "spacer"

    # write path to /etc/profile.d
    echoLog "Writing GO Path to /etc/profile.d ..."
    install -m 644 -g root -o root --backup=simple "$SK_INC/profile.d/go" /etc/profile.d/go.sh
    # write path to /etc/environment
    if ! grep -q "/usr/local/go/bin" /etc/environment; then
        echoLog "Writing GO Path to /etc/environment ..."
        while IFS= read -r line
        do
            [[ -n "$line" ]] && echo "$line" >> /etc/environment
        done < "$SK_INC/environment/go"
    fi

    echoLog "spacer"
}
#
# REMOVE FUNCTION
#
go-remove()
{
    echoLog "spacer"

    # remove go files
    echoLog "Removing GO Files ..."
    rm -Rf /usr/local/go
    # remove from /etc/profile.d
    echoLog "Removing GO from /etc/profile.d ..."
    rm -f /etc/profile.d/go.sh
    # remove from /etc/environment
    echoLog "Removing GO from /etc/environment"
    mv /etc/environment /etc/environment.bak
    grep -v 'PATH=$PATH:/usr/local/go/bin' /etc/environment.bak > /etc/environment
    chmod 0644 /etc/environment

    echoLog "spacer"
}
