#!/usr/bin/env bash
#
# ==================================================================
# src/scripts/elem/mfa
# ==================================================================
# Swarm-Kit - Self-Hosted Docker Swarm Cookbook
#
# File:         src/scripts/elem/mfa
# Author:       Ragdata
# Date:         09/01/2023
# License:      MIT License
# Copyright:    Copyright © 2022-2023 Darren Poulton (Ragdata)
# ==================================================================

# preserve rootPath
[[ -z "$rootPath" ]] && declare -gx rootPath="$PWD"

# ------------------------------------------------------------------
# FUNCTIONS
# ------------------------------------------------------------------
#
# INSTALL FUNCTION
#
mfa-install()
{
    echoLog "spacer"

    aptInstall libpam-google-authenticator

    echoLog "spacer"
}
#
# CONFIG FUNCTION
#
mfa-config()
{
    echoLog "spacer"

    echoLog "Configuring MFA"
    echo "" >> /etc/pam.d/sshd
    echo "auth required pam_google_authenticator.so" >> /etc/pam.d/sshd

    sed -i 's/ChallengeResponseAuthentication.*/ChallengeResponseAuthentication yes/' /etc/ssh/sshd_config

    echo "Answer the following questions thus:"
    echo " - Time-based tokens - y"
    echo " - update.google-authenticator - y"
    echo " - Disallow multiple uses - y"
    echo " - Permit shew of up to 4 minutes - n"
    echo " - Enable rate limiting - y"
    echo " - Then, YES - NO - YES to the big blobs of text"

    google-authenticator

    service ssh restart

    echoLog "spacer"
}
#
# REMOVE FUNCTION
#
mfa-remove()
{
    echoLog "spacer"

    aptRemove libpam-google-authenticator

    echoLog "spacer"
}
