#!/usr/bin/env bash
#
# ==================================================================
# src/scripts/elem/shellcheck
# ==================================================================
# Swarm-Kit - Self-Hosted Docker Swarm Toolkit
#
# File:         src/scripts/elem/shellcheck
# Author:       Ragdata
# Date:         02/02/2023
# License:      MIT License
# Copyright:    Copyright © 2022-2023 Darren Poulton (Ragdata)
# ==================================================================

# ------------------------------------------------------------------
# FUNCTIONS
# ------------------------------------------------------------------
#
# INSTALL FUNCTION
#
shellcheck-install()
{
    echoLog "spacer"

    aptInstall shellcheck

    echoLog "spacer"
}
#
# CONFIG FUNCTION
#
shellcheck-config()
{
    echoLog "spacer"

    echoLog "No Config Requirement"

    echoLog "spacer"
}
#
# REMOVE FUNCTION
#
shellcheck-remove()
{
    echoLog "spacer"

    aptRemove shellcheck

    echoLog "spacer"
}
