#!/usr/bin/env bash
# shellcheck disable=SC2129
# ==================================================================
# src/scripts/elem/sshd
# ==================================================================
# Swarm-Kit - Self-Hosted Docker Swarm Toolkit
#
# File:         src/scripts/elem/sshd
# Author:       Ragdata
# Date:         09/01/2023
# License:      MIT License
# Copyright:    Copyright © 2022-2023 Darren Poulton (Ragdata)
# ==================================================================

# ------------------------------------------------------------------
# FUNCTIONS
# ------------------------------------------------------------------
#
# INSTALL FUNCTION
#
sshd-install()
{
    echoLog "spacer"

    echoLog "No install requirement"

    echoLog "spacer"
}
#
# CONFIG FUNCTION
#
sshd-config()
{
    echoLog "spacer"

    echoLog "Backing up original SSH configuration"
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.original

    echoLog "Configuring SSHD"

    sed -i 's/#Port 22/Port 2022/' /etc/ssh/sshd_config
    sed -i 's/#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
    sed -i 's/#LogLevel.*/LogLevel VERBOSE/' /etc/ssh/sshd_config
    sed -i 's/ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
    sed -i 's/PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
    sed -i 's/#KerberosAuthentication.*/KerberosAuthentication no/' /etc/ssh/sshd_config
    sed -i 's/#GSSAPIAuthentication.*/GSSAPIAuthentication no/' /etc/ssh/sshd_config
    sed -i 's/#PermitEmptyPasswords.*/PermitEmptyPasswords no/' /etc/ssh/sshd_config
    sed -i 's/#IgnoreRhosts.*/IgnoreRhosts yes/' /etc/ssh/sshd_config
    sed -i 's/#HostBasedAuthentication.*/HostBasedAuthentication no/' /etc/ssh/sshd_config
    sed -i 's/#TCPKeepAlive.*/TCPKeepAlive yes/' /etc/ssh/sshd_config
    sed -i 's/#ClientAliveInterval.*/ClientAliveInterval 60/' /etc/ssh/sshd_config
    sed -i 's/#ClientAliveCountMax.*/ClientAliveCountMax 3/' /etc/ssh/sshd_config
    sed -i 's/#LoginGraceTime.*/LoginGraceTime 300/' /etc/ssh/sshd_config
    sed -i 's/#MaxAuthTries.*/MaxAuthTries 3/' /etc/ssh/sshd_config
    sed -i 's/X11Forwarding.*/#X11Forwarding no/' /etc/ssh/sshd_config

    if ! grep -q "Protocol 2" /etc/ssh/sshd_config; then
        echo >> /etc/ssh/sshd_config
        echo "Protocol 2" >> /etc/ssh/sshd_config
    fi

    if ! grep -q "${REGISTRY[SYSUSER]}" /etc/ssh/sshd_config; then
        echo >> /etc/ssh/sshd_config
        echo "AllowUsers ${REGISTRY[SYSUSER]} ${REGISTRY[MYUSER]}" >> /etc/ssh/sshd_config
    fi

    service ssh restart

    echoLog "spacer"
}
#
# REMOVE FUNCTION
#
sshd-remove()
{
    echoLog "spacer"

    echoLog "No remove requirement"

    echoLog "spacer"
}
